//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.Winform.Controls.Localisation {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chinese__Simplified_ : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public Chinese__Simplified_() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheng.Winform.Controls.Localisation.Chinese (Simplified)", typeof(Chinese__Simplified_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("zh-CHS");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public string MessageBoxCaptiton_Message {
            get {
                return ResourceManager.GetString("MessageBoxCaptiton_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部 的本地化字符串。
        /// </summary>
        public string SEPaginationDataGridView_EnumNavigationLocation_Bottom {
            get {
                return ResourceManager.GetString("SEPaginationDataGridView_EnumNavigationLocation_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        public string SEPaginationDataGridView_EnumNavigationLocation_Top {
            get {
                return ResourceManager.GetString("SEPaginationDataGridView_EnumNavigationLocation_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更大 (48x48) 的本地化字符串。
        /// </summary>
        public string SEToolStripImageSize_ExtraLarge {
            get {
                return ResourceManager.GetString("SEToolStripImageSize_ExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 (32x32) 的本地化字符串。
        /// </summary>
        public string SEToolStripImageSize_Large {
            get {
                return ResourceManager.GetString("SEToolStripImageSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 (24x24) 的本地化字符串。
        /// </summary>
        public string SEToolStripImageSize_Medium {
            get {
                return ResourceManager.GetString("SEToolStripImageSize_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小 (16x16) 的本地化字符串。
        /// </summary>
        public string SEToolStripImageSize_Small {
            get {
                return ResourceManager.GetString("SEToolStripImageSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return false;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
